### ISSUE TITLE
Login.attemptedTransition assigned but never used

### ISSUE THREAD

**Issue by greenlaw110** [przeor/react-router-flux-starter-kit#8]
In <a href='https://github.com/przeor/react-router-flux-starter-kit/blob/master/src/js/mixins/AuthenticationMixin.js#L9'><code>AuthenticationMixin.js</code></a> it assigned `transition` to `Login.attemptedTransition` static field:
![image](https://cloud.githubusercontent.com/assets/216930/8947200/4ceacf38-35db-11e5-90f2-bb67b74d708d.png)

However that static field is never used in the application. My hypothesis is it should be used in <a href='https://github.com/przeor/react-router-flux-starter-kit/blob/master/src/js/components/auth/app-login.js#L27'><code>components/auth/login.js::componentDidUpdate</code></a>:
![image](https://cloud.githubusercontent.com/assets/216930/8947246/029947d8-35dc-11e5-9b41-233c95ccd469.png)

Instead of direct the route to `/dashboard`, it shall check the `attemptedTransition` state and redirect to there if it's not `null`.

**Comment by przeor** [comment]
@greenlaw110 thanks. if you will do a pull request, then I will merge it. I see you already have fixed this part here: https://github.com/greenlaw110/react-router-flux-starter-kit/commit/f02f05dcf7343a14108557170a7d84fb2b87ec83#diff-74fd7423691685207bf4b7a5e58e5b2cR17

**Comment by przeor** [comment]
merged
